#!/bin/sh

# future loops
# for f in gitconfig screenrc vim vimrc; do ln -s ~/.dotfiles/$f ~/.$f; done

# git clone git@github.com:here/.dotfiles.git

# zsh --version
# requires > 4.3.6

rm -rf .gitconfig
rm -rf .irssi
rm -rf .oh-my-zsh
rm -rf .solarized
rm -rf .tmux.conf
rm -rf .vim
rm -rf .vimrc
rm -rf .zshrc

ln -s .dotfiles/gitconfig .gitconfig
ln -s .dotfiles/irssi .irssi
ln -s .dotfiles/oh-my-zsh .oh-my-zsh
ln -s .dotfiles/solarized .solarized
ln -s .dotfiles/tmux.conf .tmux.conf
ln -s .dotfiles/vim .vim
ln -s .dotfiles/vimrc .vimrc
ln -s .dotfiles/zshrc .zshrc
