#!/bin/sh

# future loops
# for f in gitconfig screenrc vim vimrc; do ln -s ~/.dotfiles/$f ~/.$f; done

# git clone git@github.com:here/.dotfiles.git

# zsh --version
# requires > 4.3.6

rm -rf .aliases;   ln -s .dotfiles/aliases .aliases
rm -rf .gitconfig; ln -s .dotfiles/gitconfig .gitconfig
rm -rf .irssi;     ln -s .dotfiles/irssi .irssi
rm -rf .oh-my-zsh; ln -s .dotfiles/oh-my-zsh .oh-my-zsh
rm -rf .solarized; ln -s .dotfiles/solarized .solarized
rm -rf .tmux.conf; ln -s .dotfiles/tmux.conf .tmux.conf
rm -rf .vim;       ln -s .dotfiles/vim .vim
rm -rf .vimrc;     ln -s .dotfiles/vimrc .vimrc
rm -rf .zshrc;     ln -s .dotfiles/zshrc .zshrc
